spring:
  profiles:
    active: dev # By default, the active profile is "dev". During production, it will be replaced to "prod" due to Azures environment variables.
  web:
    resources:
      add-mappings: false

#spring:
#  profiles:
#    active: prod # By default, the active profile is "dev". During production, it will be replaced to "prod" due to Azures environment variables.
#  jpa:
#    hibernate:
#      ddl-auto: none # Turn off the DDL auto generation.
api:
  endpoint:

    base-url: /api/v1
server:
  port: 80
