#spring:
#  profiles:
#    active: dev # By default, the active profile is "dev". During production, it will be replaced to "prod" due to Azures environment variables.
#  jpa:
#    hibernate:
#      ddl-auto: none # Turn off the DDL auto generation.
#api:
#  endpoint:
#    base-url: /api/v1
spring:
  datasource:
    url: jdbc:h2:mem:meteorite
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
api:
  endpoint:
      base-url: /api/v1
server:
  port: 80
